site_name: Auto-Rei

repo_url: https://github.com/mdsreq-fga-unb/2024.2-T03-AutoReiTintas

nav:
  - Início: index.md
  - Visão do Produto e Projeto: 
    - Cenário atual do cliente e do negócio: sections/product_vision/1_scenario.md
    - Solução proposta: sections/product_vision/2_solution.md
    - Estratégias de Engenharia de Software: sections/product_vision/3_strategy.md 
    - Engenharia de Requisitos: sections/product_vision/4_requirements_engineering.md
    - Cronogramas e entregas: sections/product_vision/5_timeline.md
    - Interação entre equipe e cliente: sections/product_vision/6_interaction.md
    - Lições Aprendidas Unidade 1: sections/presentations/learned_lessons_1.md
  - Sprints:
    - Sprint 0: sections/sprints/sprint0.md
  - Backlog: sections/backlog/backlog.md
  - Entregas: 
    - Entrega Unidade 1: sections/presentations/presentation_1.md
  - Como contribuir:
    - Ambiente de desenvolvimento: how_to_contribute/environment.md
  - Sobre: about.md
  - Historico: sections/product_vision

theme:
  name: material
  font:
    text: Fira Sans
  language: pt-BR
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: custom
      accent: custom

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: custom
      accent: custom

  logo: assets/logo.svg
  favicon: assets/logo.svg
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - content.code.copy
    - toc.integrate
    - content.tabs.link
    - header.autohide
  icon:
    repo: fontawesome/brands/github
plugins:
  - search

extra_css:
  - stylesheets/extra.css

extra:
  generator: false
