site_name: Auto-Rei

repo_url: https://github.com/mdsreq-fga-unb/2024.2-T03-AutoReiTintas

nav:
  - Início: index.md
  - Visão do Produto e Projeto: 
    - Visão do Produto:
      - Cenário atual do cliente e do negócio: sections/product_vision/1_scenario.md
      - Solução proposta: sections/product_vision/2_solution.md
      - Estratégias de Engenharia de Software: sections/product_vision/3_strategy.md 
    - Visão do Projeto:
      - Engenharia de Requisitos: sections/product_vision/4_requirements_engineering.md
      - Interação entre equipe e cliente: sections/product_vision/6_interaction.md
      - Cronograma: sections/product_vision/5_timeline.md
  - Backlog:
    - Requisitos de Software: sections/product_vision/7_requirements.md
    - DoR e DoD: sections/product_vision/8_dorAndDod.md
    - Backlog: sections/product_vision/9_backlog.md
  - Sprints:
    - Sprint: sections/sprints/sprints.md
    - Sprint 2: sections/sprints/sprint2.md
  - Estudos de Caso:
    - Estudo de Caso TechFix: sections/study_cases/study_case_PBB.md
    - Estudo de Caso EduConnect: sections/study_cases/study_case_USM.md
    - Estudo de Caso ConnectCare: sections/study_cases/study_case_UC.md
  - Entregas: 
    - Entrega Unidade 1: sections/presentations/presentation_1.md
    - Entrega Unidade 2: sections/presentations/presentation_2.md
    - Entrega Unidade 3: sections/presentations/presentation_3.md
  - Lições Aprendidas: sections/presentations/learned_lessons.md
  - Reuniões:
    - ATAS:
      - ATA 01-11: sections/atas/ata01-11.md
      - ATA 12-11: sections/atas/ata12-11.md
      - ATA 14-11: sections/atas/ata14-11.md
      - ATA 03-12: sections/atas/ata03-12.md
      - ATA 12-12: sections/atas/ata12-12.md
      - ATA 27-01: sections/atas/ata27-01.md
  - Arquitetura de Software: sections/architecture/arquitetura.md
  - Política de Branchs: sections/branch_policy/politica_branch.md
  - Como contribuir:
    - Ambiente de desenvolvimento: how_to_contribute/environment.md

theme:
  name: material
  font:
    text: Fira Sans
  language: pt-BR
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: custom
      accent: custom

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: custom
      accent: custom

  logo: assets/logo.svg
  favicon: assets/logo.svg
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - content.code.copy
    - toc.integrate
    - content.tabs.link
    - header.autohide
  icon:
    repo: fontawesome/brands/github
plugins:
  - search

extra_css:
  - stylesheets/extra.css

extra:
  generator: false
